[package]
name = "rust_websocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustupolis_server = "0.0.8"
tungstenite = "0.17.2"
local-ip-address = "0.4.4"